[package]
name = "rustly-problem-format"
description = "The versioned Trial package format the Rustly judge executes."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
rustly-judge-common.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
toml.workspace = true
